### PR TITLE
fix(install): specify older version to install

### PR DESCRIPTION
**Pull request by opanitch**
## Description

Adds the ability to install a specific version of Shorebird via a flag on the install script

example usage
```sh
curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash -s -- -b v1.4.7
```

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Hi @opanitch 👋 
Thanks for opening an PR! The reason we don't currently support this is because Shorebird CLI is designed to work with multiple, older versions of Flutter and we want our customers to always be using the latest version of Shorebird CLI. If there is something that broke in a newer version of the CLI please file an issue and we'd be more than happy to look into it but for now I don't think we should proceed with this because of the reasons mentioned above. Let me know if that makes sense and thanks again for the PR 🙏

**Comment by bryanoltman** [comment]
Closing because we want users to always be on the latest version of the Shorebird CLI. If there are bugs in the Shorebird CLI, please report them and we will fix them.

**Comment by opanitch** [comment]
a break in Shorebird CLI breaks our CD and then we must wait for a fix?  I don't find this to be acceptable

**Comment by bryanoltman** [comment]
I'm not yet sure that the issue reported in https://github.com/shorebirdtech/shorebird/issues/2591 is an issue with the Shorebird CLI. Seeing as the stack trace starts with something in `flutter_tool`, I think the issue is actually with the new Flutter version, which is a separate thing than the Shorebird CLI. We do allow using a specific Flutter version when releasing using the `--flutter-version` parameter.

**Pull request closed without merging**
